#include "raylib.bi"

CONST SCREEN_WIDTH = 800
CONST SCREEN_HEIGHT = 600
CONST WINDOW_TITLE = "PONG - BASIC"

REM I do not plan to add scoring system yet.
REM If anything I will rewrite that but with SDL
REM Or in diffrent BASIC dialect...

TYPE PADDLE
	X AS INTEGER
	Y AS INTEGER
	W AS INTEGER
	H AS INTEGER
END TYPE

TYPE BALL
	X AS INTEGER
	Y AS INTEGER
	R AS INTEGER
	XS AS INTEGER
	YS AS INTEGER
END TYPE

DIM AS BALL NEWBALL
NEWBALL.X = 400
NEWBALL.Y = 200
NEWBALL.R = 10
NEWBALL.XS = 7
NEWBALL.YS = 7
DIM AS Vector2 BALLPOS = (NEWBALL.X, NEWBALL.Y)
DIM AS PADDLE PADDLEL
PADDLEL.X = 5
PADDLEL.Y = 200
PADDLEL.W = 20
PADDLEL.H = 60
DIM AS PADDLE PADDLER
PADDLER.X = SCREEN_WIDTH-25
PADDLER.Y = 200
PADDLER.W = 20
PADDLER.H = 60

InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, WINDOW_TITLE)
REM For some reason I can't exit the program without that IF IsKeyPressed statement
SetTargetFPS(30)

WHILE NOT WindowShouldClose()
	BeginDrawing()
		NEWBALL.X += NEWBALL.XS : NEWBALL.Y += NEWBALL.YS
		IF NEWBALL.Y >= SCREEN_HEIGHT OR NEWBALL.Y <= 0 THEN NEWBALL.YS *= -1
		IF IsKeyDown(KEY_UP) THEN PADDLEL.Y -= 10
		IF IsKeyDown(KEY_DOWN) THEN PADDLEL.Y += 10
		IF CheckCollisionCircleRec(BALLPOS, NEWBALL.R, TYPE<Rectangle>(PADDLER.X, PADDLER.Y, PADDLER.W, PADDLER.H)) THEN NEWBALL.XS *= -1 : NEWBALL.X -= NEWBALL.R : BALLPOS.x = NEWBALL.X
		IF CheckCollisionCircleRec(BALLPOS, NEWBALL.R, TYPE<Rectangle>(PADDLEL.X, PADDLEL.Y, PADDLEL.W, PADDLEL.H)) THEN NEWBALL.XS *= -1 : NEWBALL.X += NEWBALL.R : BALLPOS.x = NEWBALL.X
		IF NEWBALL.X >= SCREEN_WIDTH-5 OR NEWBALL.X <= 5 THEN NEWBALL.X = SCREEN_WIDTH/2 : NEWBALL.Y = SCREEN_HEIGHT/2
		IF PADDLER.Y <= NEWBALL.Y THEN PADDLER.Y += 8 ELSE PADDLER.Y -= 8
		IF PADDLER.Y <= 0 THEN PADDLER.Y = 0
		IF PADDLEL.Y <= 0 THEN PADDLEL.Y = 0
		IF PADDLER.Y >= SCREEN_HEIGHT - PADDLER.H THEN PADDLER.Y = SCREEN_HEIGHT - PADDLER.H
		IF PADDLEL.Y >= SCREEN_HEIGHT - PADDLEL.H THEN PADDLEL.Y = SCREEN_HEIGHT - PADDLEL.H
		BALLPOS.x = NEWBALL.X : BALLPOS.y = NEWBALL.Y
		
		IF IsKeyPressed(KEY_ESCAPE) THEN EXIT WHILE ' <-- here
		
			ClearBackground(BLACK)

		DrawRectangle(PADDLEL.X, PADDLEL.Y, PADDLEL.W, PADDLEL.H, RED)
		DrawRectangle(PADDLER.X, PADDLER.Y, PADDLER.W, PADDLER.H, RED)
		DrawCircleV(BALLPOS, NEWBALL.R, RED)
		DrawText("Free BASIC, Press ESC to exit.", 20, 20, 10, RED)
	EndDrawing()
WEND

CloseWindow()
